import type { CinematicSceneConfig, SpatialConfig } from "@/src/lib/cinematic/schema";

export const cinematicPresets = {
  architecturalThreshold(id:string):CinematicSceneConfig{return{id,stack:{enabled:true,scaleTo:.92,darkenTo:.34,depth:72,overlap:.24,pin:true},spring:{mass:1,stiffness:160,damping:25,precision:.001,maxStep:1/30},reveal:{effect:"directional",direction:"right",softness:.12,intensity:1,pointerInfluence:0,trailInfluence:0,edgeColor:"#f5e8d4",edgeWidth:.008,seed:47,range:[0,1]},procedural:[],occlusion:[{id:"threshold-shadow",kind:"shadow",range:[.62,.96],axis:"x",from:110,to:-110,blur:20,opacity:.55,depth:1}]};},
  spatialPhotoHero(id:string,spatial:SpatialConfig):CinematicSceneConfig{return{id,stack:{enabled:true,scaleTo:.94,darkenTo:.28,depth:48,overlap:.2,pin:true},spring:{mass:1,stiffness:145,damping:22,precision:.001,maxStep:1/30},reveal:{effect:"liquid",direction:"right",softness:.18,intensity:1,pointerInfluence:.7,trailInfluence:.8,edgeColor:"#ffffff",edgeWidth:.01,seed:71,range:[0,1]},spatial,procedural:[],occlusion:[]};},
  technicalReveal(id:string):CinematicSceneConfig{return{id,reveal:{effect:"wireframe",direction:"right",softness:.1,intensity:1,pointerInfluence:.2,trailInfluence:.2,edgeColor:"#f97316",edgeWidth:.014,seed:88,range:[.05,.88]},procedural:[{id:"technical-contours",kind:"contours",opacity:.52,color:"#ffffff",range:[0,1],blendMode:"screen",interactive:true,seed:31,count:22,amplitude:.42,frequency:2.4}],occlusion:[]};},
  editorialTransition(id:string):CinematicSceneConfig{return{id,stack:{enabled:true,scaleTo:.9,darkenTo:.55,depth:96,overlap:.3,pin:true},reveal:{effect:"burn",direction:"right",softness:.08,intensity:1.2,pointerInfluence:.1,trailInfluence:.15,edgeColor:"#f97316",edgeWidth:.02,seed:145,range:[.08,.92]},procedural:[],occlusion:[{id:"editorial-blur",kind:"blur",range:[.55,.92],axis:"x",from:100,to:-100,blur:34,opacity:.62,depth:2}]};},
  luxuryMaterial(id:string):CinematicSceneConfig{return{id,spring:{mass:.9,stiffness:125,damping:23,precision:.001,maxStep:1/30},reveal:{effect:"radial",direction:"right",softness:.2,intensity:.9,pointerInfluence:1.1,trailInfluence:.3,edgeColor:"#eadbc5",edgeWidth:.007,seed:204,range:[.05,.96]},procedural:[{id:"material-grid",kind:"grid",opacity:.16,color:"#eadbc5",range:[.05,.95],blendMode:"screen",interactive:true,seed:9,columns:16,rows:10,distortion:.18}],occlusion:[]};},
} as const;
