import type { CinematicSceneConfig, SpatialConfig } from "@/src/lib/cinematic/schema";

export const cinematicPresets = {
  architecturalThreshold(id:string):CinematicSceneConfig{return{id,stack:{enabled:true,scaleTo:.92,darkenTo:.34,depth:72,overlap:.24,pin:true},spring:{mass:1,stiffness:160,damping:25,precision:.001,maxStep:1/30},reveal:{effect:"directional",direction:"right",softness:.12,intensity:1,pointerInfluence:0,trailInfluence:0,edgeColor:"#f5e8d4",edgeWidth:.008,seed:47,range:[0,1]},procedural:[],occlusion:[{id:"threshold-shadow",kind:"shadow",range:[.62,.96],axis:"x",from:110,to:-110,blur:20,opacity:.55,depth:1}]};},
  spatialPhotoHero(id:string,spatial:SpatialConfig):CinematicSceneConfig{return{id,stack:{enabled:true,scaleTo:.94,darkenTo:.28,depth:48,overlap:.2,pin:true},spring:{mass:1,stiffness:145,damping:22,precision:.001,maxStep:1/30},reveal:{effect:"liquid",direction:"right",softness:.18,intensity:1,pointerInfluence:.7,trailInfluence:.8,edgeColor:"#ffffff",edgeWidth:.01,seed:71,range:[0,1]},spatial,procedural:[],occlusion:[]};},
  technicalReveal(id:string):CinematicSceneConfig{return{id,reveal:{effect:"wireframe",direction:"right",softness:.1,intensity:1,pointerInfluence:.2,trailInfluence:.2,edgeColor:"#f97316",edgeWidth:.014,seed:88,range:[.05,.88]},procedural:[{id:"technical-contours",kind:"contours",opacity:.52,color:"#ffffff",range:[0,1],blendMode:"screen",interactive:true,seed:31,count:22,amplitude:.42,frequency:2.4}],occlusion:[]};},
  editorialTransition(id:string):CinematicSceneConfig{return{id,stack:{enabled:true,scaleTo:.9,darkenTo:.55,depth:96,overlap:.3,pin:true},reveal:{effect:"burn",direction:"right",softness:.08,intensity:1.2,pointerInfluence:.1,trailInfluence:.15,edgeColor:"#f97316",edgeWidth:.02,seed:145,range:[.08,.92]},procedural:[],occlusion:[{id:"editorial-blur",kind:"blur",range:[.55,.92],axis:"x",from:100,to:-100,blur:34,opacity:.62,depth:2}]};},
  luxuryMaterial(id:string):CinematicSceneConfig{return{id,spring:{mass:.9,stiffness:125,damping:23,precision:.001,maxStep:1/30},reveal:{effect:"radial",direction:"right",softness:.2,intensity:.9,pointerInfluence:1.1,trailInfluence:.3,edgeColor:"#eadbc5",edgeWidth:.007,seed:204,range:[.05,.96]},procedural:[{id:"material-grid",kind:"grid",opacity:.16,color:"#eadbc5",range:[.05,.95],blendMode:"screen",interactive:true,seed:9,columns:16,rows:10,distortion:.18}],occlusion:[]};},
  cursorReveal(id:string,src="/textures/reference/reveal-field.svg"):CinematicSceneConfig{return{id,cursorReveal:{src,mode:"trail",renderer:"auto",brushSize:.14,brushStrength:1,softness:.22,motionStrength:1,lingerMs:280,fadeSeconds:1.25,trailPersistence:.84,touch:"drag",fit:"cover",position:[50,50],fluidResolution:192,velocityDissipation:.985,dyeDissipation:.992,pressureIterations:12,curl:18,splatForce:4},procedural:[],occlusion:[]};},
  warpSurface(id:string):CinematicSceneConfig{return{id,warp:{mode:"elastic",strength:.42,radius:.32,falloff:2,pointerInfluence:1,velocityInfluence:.72,scrollInfluence:.22,frequency:8},procedural:[],occlusion:[]};},
  refractiveSurface(id:string):CinematicSceneConfig{return{id,refraction:{mode:"liquid",strength:.3,radius:.36,dispersion:.009,edgeRefraction:.48,sheen:.24,ripple:.22,pointerInfluence:1,center:[50,50]},procedural:[],occlusion:[]};},
  shaderTransition(id:string,src?:string):CinematicSceneConfig{return{id,sceneTransition:{effect:"liquid",src,range:[.72,1],direction:"right",softness:.08,intensity:1,displacement:.05,chromaticAberration:.008,blockSize:24,slats:12,seed:47},procedural:[],occlusion:[]};},
  visualPhysics(id:string,src?:string):CinematicSceneConfig{return{id,warp:{mode:"water",strength:.28,radius:.34,falloff:2.4,pointerInfluence:.9,velocityInfluence:.65,scrollInfluence:.2,frequency:9},refraction:{mode:"lens",strength:.22,radius:.34,dispersion:.007,edgeRefraction:.38,sheen:.18,ripple:.16,pointerInfluence:.9,center:[50,50]},sceneTransition:{effect:"chromatic",src,range:[.76,1],direction:"right",softness:.07,intensity:.9,displacement:.035,chromaticAberration:.012,blockSize:24,slats:12,seed:71},procedural:[],occlusion:[]};},
} as const;
