import type { DirectorBrief, DirectorTerritory, DirectorTreatment } from "@/src/platform/directorSchema";

export type AudienceLensId = "first-time" | "high-intent" | "skeptical-buyer" | "technical-evaluator" | "luxury-buyer" | "time-poor-executive" | "mobile" | "reduced-motion";
export interface AudienceLensResult { lens: AudienceLensId; noticesFirst: string; confusion: string[]; trust: string[]; desire: string[]; friction: string[]; missingProof: string[]; leaveRisk: string[]; confidence: number; evidenceClass: "director-inference"; }

export function simulateAudienceLenses(brief: DirectorBrief, treatment: DirectorTreatment, territory: DirectorTerritory): AudienceLensResult[] {
  const signature = territory.signatureMoment;
  const firstBeat = treatment.emotionalArc[0];
  const proofBeats = treatment.emotionalArc.filter((beat) => beat.proofLevel >= 6);
  const conversionBeat = treatment.emotionalArc.find((beat) => beat.conversionWeight >= 8);
  const common = { evidenceClass: "director-inference" as const, confidence: 0.55 };
  return [
    { lens: "first-time", noticesFirst: firstBeat?.purpose ?? territory.thesis, confusion: firstBeat?.visitorQuestion ? [] : ["Opening question is unclear."], trust: proofBeats.length ? ["Proof exists later in the journey."] : [], desire: [signature], friction: treatment.emotionalArc.length > 10 ? ["Long journey before full understanding."] : [], missingProof: proofBeats.length ? [] : ["No high-proof chapter."], leaveRisk: firstBeat?.intensity && firstBeat.intensity > 8 ? ["Opening may spend climax energy too early."] : [], ...common },
    { lens: "high-intent", noticesFirst: brief.primaryAction, confusion: [], trust: proofBeats.map((beat) => beat.label), desire: [territory.memory], friction: conversionBeat ? [] : ["Primary action arrives without an explicit high-intent chapter."], missingProof: proofBeats.length ? [] : ["Needs proof near action."], leaveRisk: treatment.conversionArc.length ? [] : ["Utility path may be hidden by storytelling."], ...common },
    { lens: "skeptical-buyer", noticesFirst: territory.strategicReason, confusion: [], trust: brief.differentiators.slice(0, 3), desire: [territory.memory], friction: territory.scores.feasibility < 7 ? ["Concept may feel like promise before proof."] : [], missingProof: brief.differentiators.length ? [] : ["Client differentiators are not explicit."], leaveRisk: proofBeats.length < 1 ? ["Insufficient evidence to justify premium positioning."] : [], ...common },
    { lens: "technical-evaluator", noticesFirst: treatment.productionPriorities.join("; "), confusion: [], trust: treatment.assets.filter((asset) => asset.quality === "hero" || asset.quality === "strong").map((asset) => asset.label), desire: [], friction: treatment.signatureMoment.prerequisites.length > 3 ? ["Signature has many dependencies."] : [], missingProof: treatment.assets.length ? [] : ["No asset inventory supplied."], leaveRisk: territory.scores.feasibility < 7 ? ["Execution risk appears high."] : [], ...common },
    { lens: "luxury-buyer", noticesFirst: territory.memory, confusion: [], trust: proofBeats.map((beat) => beat.purpose), desire: [signature], friction: treatment.emotionalArc.filter((beat) => beat.informationDensity >= 8).length > 2 ? ["Information density may reduce premium calm."] : [], missingProof: [], leaveRisk: treatment.emotionalArc.filter((beat) => beat.intensity >= 8).length > 3 ? ["Too many peaks can make the experience feel promotional rather than assured."] : [], ...common },
    { lens: "time-poor-executive", noticesFirst: territory.thesis, confusion: territory.thesis.length > 180 ? ["Thesis may take too long to parse."] : [], trust: brief.differentiators.slice(0, 2), desire: [territory.memory], friction: treatment.emotionalArc.length > 8 ? ["Full journey is long; provide skip/summary utility."] : [], missingProof: [], leaveRisk: !conversionBeat ? ["Decision path is not immediate enough."] : [], ...common },
    { lens: "mobile", noticesFirst: treatment.mobileInterpretation[0] ?? territory.thesis, confusion: [], trust: [], desire: [territory.memory], friction: treatment.mobileInterpretation.length < 2 ? ["Mobile-specific direction is sparse."] : [], missingProof: [], leaveRisk: treatment.mobileInterpretation.length === 0 ? ["Desktop concept may collapse on mobile."] : [], ...common },
    { lens: "reduced-motion", noticesFirst: territory.thesis, confusion: [], trust: proofBeats.map((beat) => beat.label), desire: [territory.memory], friction: treatment.mobileInterpretation.some((rule) => /reduced|static|poster/i.test(rule)) ? [] : ["Reduced-motion equivalence is not explicit."], missingProof: [], leaveRisk: /motion|camera|orbit|fly|scroll/i.test(territory.thesis) ? ["Thesis wording itself may depend on motion rather than meaning."] : [], ...common },
  ];
}
