import type { ImmersiveReference } from "@/src/platform/director-intelligence/referenceCorpus";

const REVIEWED_AT = "2026-09-18";
const doNotCopy = [
  "Exact palette",
  "Exact typeface",
  "Branded copy or assets",
  "Distinctive signature composition without a new client-specific reason",
  "A proprietary interaction sequence verbatim",
];

function caseStudy(
  id: string,
  title: string,
  source: string,
  industry: string,
  observedTraits: string[],
  transferableLessons: string[],
  constructionPatternIds: string[],
  evidenceNotes: string[],
  confidence = 0.92,
  evidenceLevel: ImmersiveReference["evidenceLevel"] = "public-case-study",
): ImmersiveReference {
  return {
    id,
    title,
    source,
    industry,
    access: "free",
    evidenceLevel,
    reviewedAt: REVIEWED_AT,
    confidence,
    observedTraits,
    transferableLessons,
    constructionPatternIds,
    evidenceNotes,
    doNotCopy,
  };
}

/**
 * Broader immersive-web construction corpus.
 *
 * These references come from public studio case studies and technical
 * breakdowns. They exist to keep Forge from overfitting to one marketplace or
 * one visual style. The records encode construction principles, not source code.
 */
export const broaderImmersiveReferenceCorpus: ImmersiveReference[] = [
  caseStudy(
    "dogstudio-virgin-galactic",
    "Virgin Galactic",
    "https://dogstudio.co/cases/virgin-galactic/",
    "Brand / Aerospace",
    [
      "Multiple WebGL subscenes are connected through planned transitions rather than treated as independent pages.",
      "Media cards and hotspots layer text, audio and video context into explorable 3D environments.",
      "Reflection quality is simulated with multiple pre-rendered environment maps blended by camera position rather than expensive realtime reflection.",
      "A front-end/WebGL event system coordinates semantic interface and 3D scene behavior.",
    ],
    [
      "Plan transitions between heavy 3D chapters as an asset/performance problem before polishing their visuals.",
      "Use contextual cards and hotspots to add information without breaking the spatial world.",
      "Fake expensive optics when a precomputed representation preserves the visual result at much lower cost.",
      "Define an explicit communication contract between DOM interaction state and WebGL state.",
    ],
    ["multi-subscene-transition-budget", "context-layer-over-world", "simulated-expensive-lighting", "dom-webgl-contract"],
    ["Dogstudio public case study describes WebGL subscenes, media cards/hotspots, environment-map reflection strategy and front-end/WebGL event architecture."],
  ),
  caseStudy(
    "dogstudio-zoox",
    "Zoox",
    "https://dogstudio.co/cases/zoox/",
    "Automotive / Technology",
    [
      "Realtime WebGL was chosen specifically to balance fidelity and asset weight.",
      "The 3D pipeline was developed closely with the client's lead 3D artist rather than treating web optimization as a post-production step.",
    ],
    [
      "Choose realtime 3D when it reduces media weight or enables continuity that pre-rendered video cannot provide.",
      "Bring 3D artists and runtime engineers into the same optimization loop early.",
    ],
    ["staged-subject-hero", "adaptive-fidelity-not-removal"],
    ["Dogstudio public case study explicitly frames WebGL as a fidelity/load-time tradeoff and describes close collaboration with Zoox's 3D artist."],
  ),
  caseStudy(
    "dogstudio-geske",
    "Geske",
    "https://dogstudio.co/cases/geske/",
    "E-commerce / Beauty",
    [
      "Product narrative blends emotional imagery with technical detail rather than separating brand story and product proof.",
      "3D product models are optimized through polygon reduction, compression, lazy loading and adaptive loading across connection/device conditions.",
      "Lines and particle shaders visualize the relationship between engineering, skincare expertise and AI rather than existing as decoration.",
    ],
    [
      "Use abstract WebGL systems to explain a product relationship or process, not merely to create atmosphere.",
      "Treat geometry, compression, lazy loading and network/device adaptation as one asset-delivery policy.",
      "Keep emotional storytelling and technical proof in the same narrative arc.",
    ],
    ["embedded-proof-in-hero", "adaptive-fidelity-not-removal", "procedural-field-as-hero"],
    ["Dogstudio public case study documents the multilingual narrative strategy and WebGL optimization techniques."],
  ),
  caseStudy(
    "dogstudio-dept-pioneer",
    "DEPT Pioneer",
    "https://dogstudio.co/cases/dept-pioneer/",
    "Agency / Studio",
    [
      "Visitors can choose a guided conversational path or bypass it for direct access to content.",
      "The WebGL experience is tightly coupled to the front-end rather than functioning as a separate intro.",
    ],
    [
      "Immersive navigation can offer a directed route and a direct route simultaneously.",
      "Do not force every visitor through the signature sequence when high-intent users may need immediate access.",
    ],
    ["context-layer-over-world", "dom-webgl-contract"],
    ["Dogstudio public case study describes the two navigation paths and coupled WebGL/front-end architecture."],
  ),
  caseStudy(
    "dogstudio-meebits",
    "Meebits",
    "https://dogstudio.co/cases/meebits/",
    "Product / Community",
    [
      "A single ON/OFF interaction changes the character from static presentation into an animated state.",
      "The project keeps the character as the primary focus while expanding functionality into moods, customization and capture.",
      "Typography, icons, motion and sound all obey the same pixel-world language.",
    ],
    [
      "A binary state change can be more memorable than several small hover effects when it transforms the subject and interface together.",
      "Let secondary features extend the hero subject rather than competing with it.",
      "Use one world grammar across type, sound, iconography and motion.",
    ],
    ["interaction-as-thesis", "anchor-section-sets-system", "single-signature-peak"],
    ["Dogstudio public case study describes the ON/OFF transformation and later mood/capture states."],
  ),
  caseStudy(
    "dogstudio-tomorrowland",
    "Tomorrowland Around the World",
    "https://staging.dogstudio.co/cases/tomorrowland/",
    "Entertainment / Festival",
    [
      "The same world supports both day and night states tied to event timing.",
      "Boats, lights, fish, god rays, butterflies and clouds are small environmental systems used to sell one coherent world.",
      "The experience was built for both mobile and desktop.",
    ],
    [
      "Reuse one environment across meaningful state changes instead of building separate disconnected worlds.",
      "Small ambient systems should reinforce place, time and story rather than add generic particles.",
      "Translate the same world concept across devices.",
    ],
    ["single-world-under-interface", "atmosphere-as-layout", "mobile-preserve-concept"],
    ["Dogstudio public case study describes day/night modes, environmental detail systems and mobile/desktop immersive delivery."],
  ),
  caseStudy(
    "dogstudio-adobe-taking-shape",
    "Adobe Taking Shape",
    "https://staging.dogstudio.co/cases/adobe-taking-shape/",
    "Culture / Education",
    [
      "Early 2D concepts were revised because they did not translate cleanly to 3D camera movement.",
      "Late feature additions were survivable because the WebGL codebase kept a clean internal architecture.",
    ],
    [
      "Judge reference concepts for 3D camera compatibility before production; a strong flat composition may fail when spatialized.",
      "Clean scene contracts make late creative additions less destructive.",
    ],
    ["authored-camera-corridor", "dom-webgl-contract"],
    ["Dogstudio public case study explicitly notes the difficulty translating initial 2D designs into 3D environments/camera movement and credits clean WebGL architecture for later adaptation."],
  ),
  caseStudy(
    "dogstudio-kikk-2018",
    "KIKK Festival 2018",
    "https://staging.dogstudio.co/cases/kikk-festival-2018/",
    "Culture / Festival",
    [
      "Hand-drawn organisms are contrasted with rigorous 19th-century scientific grids and captions.",
      "The same identity language is carried across images, hover states, transitions and WebGL/canvas animation.",
    ],
    [
      "Immersive art direction becomes stronger when two contrasting visual systems have a clear conceptual reason.",
      "Carry the identity into hover and transition behavior instead of treating motion as a separate style layer.",
    ],
    ["technical-chrome-world-language", "anchor-section-sets-system"],
    ["Dogstudio public case study explains the intentional tension between playful organisms and scientific-book design codes."],
  ),
  caseStudy(
    "lusion-devin-ai",
    "Devin AI",
    "https://lusion.co/projects/devin_ai/",
    "AI / Tech",
    [
      "Complex AI product information is presented through subtle storytelling, animation and interactive design rather than maximal spectacle.",
      "3D and WebGL support an advanced-but-approachable product tone.",
    ],
    [
      "For complex products, use motion to clarify sequencing before using it to impress.",
      "Advanced visual technology can remain visually quiet when trust and comprehension are the primary objectives.",
    ],
    ["immersive-without-webgl", "density-rhythm-and-silence"],
    ["Lusion public case study describes a clear, sleek, accessible AI product story supported by subtle storytelling and interactive design."],
  ),
  caseStudy(
    "lusion-zero-tech",
    "Zero Tech",
    "https://lusion.co/projects/zero_tech/",
    "AI / Tech",
    [
      "Realtime 3D visuals are directly fused with scroll navigation.",
      "The visual experience is used to communicate innovation rather than being isolated as a separate 3D module.",
    ],
    [
      "Bind the central 3D state to scroll structure so content progression and visual progression are the same system.",
    ],
    ["continuous-visual-anchor", "scroll-reposition-not-reset", "dom-webgl-contract"],
    ["Lusion public case study explicitly describes merging realtime 3D visuals and scroll navigation."],
  ),
  caseStudy(
    "lusion-max-mara-bearing-gifts",
    "Max Mara: Bearing Gifts",
    "https://lusion.co/projects/maxmara_bearings_gifts/",
    "Fashion / Commerce",
    [
      "A character guides visitors through playful scenes and product showcases.",
      "Render quality, timeline and budget are planned together.",
      "Non-realtime lighting is used to keep the experience consistent across devices.",
    ],
    [
      "A recurring character can act as a continuity anchor across product chapters.",
      "Choose baked/precomputed lighting when it preserves the desired look with better device consistency.",
      "Creative scope, frame budget and production timeline should be negotiated together.",
    ],
    ["continuous-visual-anchor", "simulated-expensive-lighting", "adaptive-fidelity-not-removal"],
    ["Lusion public case study describes character-led scenes, cross-device planning and non-realtime lighting for performance."],
  ),
  caseStudy(
    "lusion-of-the-oak",
    "Of The Oak",
    "https://lusion.co/projects/of_the_oak/",
    "Culture / Installation",
    [
      "Complex Houdini tree/branch/node data is compressed into a custom 3.5 MB web format.",
      "WebGL instancing is used to render repeated structures efficiently.",
    ],
    [
      "When source 3D data is structurally repetitive, redesign the asset format for the web instead of shipping the authoring structure.",
      "Use instancing when repeated geometry carries the visual idea.",
    ],
    ["source-structure-to-runtime-format", "gpu-progress-transforms"],
    ["Lusion public case study documents a Houdini-to-WebGL compression pipeline and instancing."],
  ),
  caseStudy(
    "lusion-worldcoin-globe",
    "Worldcoin Globe",
    "https://lusion.co/projects/worldcoin/",
    "Data / Technology",
    [
      "Country and dot data are compressed into image data and decoded for GPU rendering.",
      "Visual effects can be activated by live registration data through an API.",
    ],
    [
      "Encode dense spatial data into GPU-friendly textures when object-by-object transfer would be too heavy.",
      "When data is meaningful, let real data drive visual state rather than simulating activity.",
    ],
    ["source-structure-to-runtime-format", "data-drives-world-state"],
    ["Lusion public case study documents image-based data compression, GPU rendering and APIs for live visual activation."],
  ),
  caseStudy(
    "lusion-turn-of-the-screw",
    "The Turn of the Screw Trailer",
    "https://v2.lusion.co/work/the-turn-of-the-screw-trailer/",
    "Culture / Performance",
    [
      "Navigation follows predefined camera splines authored to match physical camera settings from Houdini.",
      "Polygons never visible from the camera corridor are removed offline.",
      "Hovering a singer changes both light and audio focus, tying two sensory channels to one interaction.",
    ],
    [
      "Author difficult camera paths in the DCC tool when precise framing matters, then preserve those camera semantics in WebGL.",
      "Cull geometry against the actual reachable camera volume, not an imaginary free camera.",
      "One interaction can coordinate visual and audio emphasis when both express the same intent.",
    ],
    ["authored-camera-corridor", "camera-corridor-culling", "interaction-as-thesis"],
    ["Lusion technical case study describes Houdini camera splines, camera-volume polygon visibility tests, and synchronized visual/audio focus."],
    0.97,
    "technical-reference",
  ),
  caseStudy(
    "lusion-ion",
    "ION / X1",
    "https://exp-ion.lusion.co/",
    "Product / Concept",
    [
      "A conceptual speaker launch uses one coherent design language across modeling, texturing, shaders, lighting and UI.",
      "The 3D product itself is the center of the landing page rather than a detached demo viewer.",
    ],
    [
      "Treat modeling, materials, lighting and interface as one art-direction system.",
      "A product hero becomes more convincing when every rendering decision reinforces the same material story.",
    ],
    ["staged-subject-hero", "anchor-section-sets-system"],
    ["Lusion public experiment page describes a real-time product landing page focused on cohesive 3D and UI design language."],
  ),
  caseStudy(
    "lusion-my-little-storybook",
    "My Little Storybook",
    "https://lusion.co/projects/my_little_story_book/",
    "Culture / Storytelling",
    [
      "Hand-drawn sketches are intentionally blended into a 3D WebGL environment.",
      "The visual style is built around the collision of crafted 2D and 3D rather than photorealism.",
    ],
    [
      "Stylized 2D assets can become part of a 3D world when the mixed-medium relationship is deliberate.",
      "Do not assume realism is the goal of immersive 3D; consistency of art direction matters more.",
    ],
    ["mixed-media-world", "anchor-section-sets-system"],
    ["Lusion public case study describes blending hand-drawn sketches with custom 3D assets in WebGL."],
  ),
  caseStudy(
    "makemepulse-riot-anima-squad",
    "Riot Anima Squad",
    "https://www.makemepulse.com/case-study/riot-anima-squad",
    "Gaming",
    [
      "Y2K visual language is carried through motion, hidden easter eggs and WebGL enemy showcases.",
      "Twelve enemies are presented as pre-game exploration with tactical/trait context.",
    ],
    [
      "Interactive collections are strongest when exploration teaches something useful about each item.",
      "Easter eggs should reward curiosity after the core information architecture works.",
    ],
    ["spatial-gallery-rhythm", "context-layer-over-world"],
    ["Makemepulse public case study describes Y2K motion language, easter eggs and a WebGL showcase of 12 enemies."],
  ),
  caseStudy(
    "makemepulse-audemars-piguet-house-of-wonders",
    "Audemars Piguet: The House of Wonders",
    "https://www.makemepulse.com/case-study/audemars-piguet-the-house-of-wonders",
    "Luxury / Watchmaking",
    [
      "Three symbolic spaces correspond to three stages in the transformation of an idea.",
      "The same experience is designed for desktop, mobile and VR with 3D environments, narration and sound.",
    ],
    [
      "Make each spatial environment represent a narrative concept, not simply a visual theme.",
      "Cross-device immersive work should preserve story structure while adapting input and rendering.",
    ],
    ["threshold-passage", "mobile-preserve-concept", "single-signature-peak"],
    ["Makemepulse public case study describes three symbolic spaces and cross-device WebGL/WebXR delivery."],
  ),
  caseStudy(
    "makemepulse-weleda-open-garden",
    "Weleda: The Open Garden",
    "https://www.makemepulse.com/case-study/weleda-the-open-garden",
    "Wellness / Nature",
    [
      "A mobile-first experience uses enhanced 360-degree environments rather than a free-roaming heavy 3D world.",
      "Custom animations and interactive elements are layered into the 360 scenes.",
      "Transitions between environments are kept smooth and quick to preserve narrative flow.",
    ],
    [
      "Choose 360 media when spatial presence matters more than free camera movement.",
      "Layer interaction into a lighter spatial medium rather than defaulting to full geometry.",
      "Fast transitions can preserve continuity better than technically elaborate scene swaps.",
    ],
    ["choose-medium-by-capability", "multi-subscene-transition-budget", "mobile-preserve-concept"],
    ["Makemepulse public case study describes mobile-first enhanced 360 environments and smooth inter-environment transitions."],
  ),
  caseStudy(
    "makemepulse-nasdaq-50",
    "Nasdaq 50th Anniversary",
    "https://www.makemepulse.com/case-study/nasdaq-50th-anniversary/",
    "Finance / History",
    [
      "A WebGL timeline combines employee content, museum material and news archives into one historical exhibition.",
      "The experience is explicitly mobile-first despite using animation, 3D and motion design.",
    ],
    [
      "For archive-heavy experiences, spatialize chronology rather than forcing content into disconnected cards.",
      "Historical proof can become the immersive material itself.",
    ],
    ["timeline-as-exhibition", "mobile-preserve-concept"],
    ["Makemepulse public case study describes an interactive WebGL timeline built from archival material and a mobile-first approach."],
  ),
  caseStudy(
    "makemepulse-la-prairie-harmony",
    "La Prairie: The Pursuit of Harmony",
    "https://www.makemepulse.com/case-study/la-prairie-the-pursuit-of-harmony",
    "Luxury / Beauty",
    [
      "Three rooms separate exhibition, product innovation and scientific process while remaining within one Bauhaus-inspired world.",
      "The experience uses art and science as complementary narrative systems.",
    ],
    [
      "Different content modes can occupy separate spatial rooms when one visual grammar keeps them coherent.",
      "Use spatial structure to distinguish emotional, product and technical information without breaking continuity.",
    ],
    ["threshold-passage", "anchor-section-sets-system", "embedded-proof-in-hero"],
    ["Makemepulse public case study describes three rooms for exhibition, product and science inside one art-direction system."],
  ),
  caseStudy(
    "makemepulse-world-with-no-heroes",
    "A World With No Heroes",
    "https://www.makemepulse.com/news/a-world-with-no-heroes",
    "Gaming / Storytelling",
    [
      "A real-time 3D map contains 50 surveillance cameras and up to eight hours of teaser content.",
      "Autonomous systemic events trigger content throughout the world.",
      "The map supports day and night states.",
    ],
    [
      "Large worlds need content systems, not only scenery; events and cameras turn space into narrative navigation.",
      "Use systemic events to make a persistent world feel alive without scripting every frame manually.",
    ],
    ["single-world-under-interface", "data-drives-world-state", "context-layer-over-world"],
    ["Makemepulse behind-the-scenes article describes the real-time map, 50 cameras, autonomous events and day/night exploration."],
    0.97,
    "technical-reference",
  ),
  caseStudy(
    "bonhomme-black-messiah",
    "Black Messiah",
    "https://bonhommeparis.com/en/projects/black-messiah",
    "Culture / Storytelling",
    [
      "Five interactive scenes each expose a central story theme.",
      "Interacting with a word changes the meaning of a sentence and makes the visitor causally responsible for narrative interpretation.",
    ],
    [
      "Interaction becomes memorable when it changes meaning, not only appearance.",
      "A small language interaction can carry the thesis of an immersive world.",
    ],
    ["interaction-as-thesis", "single-signature-peak"],
    ["Bonhomme public case study explicitly describes five scenes and a word interaction that changes sentence meaning."],
  ),
  caseStudy(
    "bonhomme-tag-heuer-skipper",
    "TAG Heuer Skipper",
    "https://bonhommeparis.com/en/projects/th-skipper",
    "Luxury / Watchmaking",
    [
      "The landing page alternates between an immersive 3D sailing scene and rational product information panels.",
      "Transitions create the relationship between those two dimensions.",
      "The experience was designed mobile-first and the boat/ocean were optimized for WebGL accordingly.",
    ],
    [
      "Luxury product storytelling benefits from an explicit contract between emotional spatial world and rational product proof.",
      "Transitions should explain the change from immersive scene to product information instead of cutting between two unrelated modes.",
      "If mobile is the primary traffic source, model/scene budgets should start from mobile constraints.",
    ],
    ["immersive-rational-duality", "multi-subscene-transition-budget", "mobile-preserve-concept"],
    ["Bonhomme public case study describes the 3D-vs-information-panel duality, natural transitions and mobile-first WebGL optimization."],
  ),
  caseStudy(
    "bonhomme-tag-heuer-carrera-60",
    "TAG Heuer Carrera 60th",
    "https://bonhommeparis.com/en/projects/th-carrera-60",
    "Luxury / Watchmaking",
    [
      "A realistic 3D watch is progressively revealed from multiple angles through browsing.",
      "The product story and race heritage are structured as a progressive narrative.",
    ],
    [
      "Use changing camera angles as chapters in a product argument, not as free orbit.",
      "Tie product reveal to historical/brand narrative so the object earns each new view.",
    ],
    ["staged-subject-hero", "macro-whole-rhythm", "authored-camera-corridor"],
    ["Bonhomme public case study describes a progressive narrative using a realistic 3D watch revealed from multiple angles."],
  ),
  caseStudy(
    "bonhomme-ten-years",
    "Bonhomme 10 Years",
    "https://bonhommeparis.com/en/projects/bonhomme",
    "Agency / Studio",
    [
      "Ten values are expressed through scene-by-scene character interactions.",
      "High technical complexity is deliberately hidden behind a naive black-and-white illustrated world.",
      "Navigation is one of the few deliberately digital-looking elements.",
    ],
    [
      "Technology should disappear behind art direction when visible technicality would weaken the concept.",
      "Reserve overtly digital UI language for the places where it clarifies navigation or control.",
    ],
    ["mixed-media-world", "edge-utility-central-spectacle"],
    ["Bonhomme public case study explicitly states that WebGL/3D technicality is hidden behind an illustrative universe."],
  ),
  caseStudy(
    "14islands-hatom",
    "Hatom / Syfy + USH",
    "https://www.14islands.com/work/hatom",
    "Fintech / Web3",
    [
      "Syfy uses interactive 3D cubes as containers for subsidiary profiles.",
      "USH uses cosmic visuals and smooth-scrolling animation to explain stablecoin features.",
    ],
    [
      "Choose a spatial metaphor that matches content structure: container-like cubes for a portfolio of entities, continuous cosmic travel for feature storytelling.",
      "The same studio can use different immersive grammars for adjacent products instead of imposing one signature effect everywhere.",
    ],
    ["object-prop-depth-stage", "continuous-visual-anchor"],
    ["14islands public case study describes interactive 3D cubes for Syfy and cosmic smooth-scroll storytelling for USH."],
  ),
  caseStudy(
    "codrops-zero",
    "ZERO",
    "https://tympanus.net/codrops/2026/07/17/zero-the-engineering-behind-a-defiant-interactive-narrative/",
    "Experimental / Portfolio",
    [
      "Entry is gated by drawing a zero rather than clicking a conventional enter button.",
      "The gesture is validated through signed angle, roundness and closure, then seeds a frost shader reveal.",
      "The entrance interaction teaches the visual language before the main experience begins.",
    ],
    [
      "A custom entry gesture is justified when it expresses the concept and immediately controls the first visual transformation.",
      "Validate semantic gesture properties instead of matching raw pointer paths.",
    ],
    ["interaction-as-thesis", "gesture-gates-world"],
    ["Codrops technical case study documents the gesture validation and frost-shader reveal."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-ten-years-away",
    "Ten Years Away",
    "https://tympanus.net/codrops/2026/07/08/ten-years-away-designing-an-interactive-comic-for-studio375s-tenth-anniversary/",
    "Portfolio / Storytelling",
    [
      "A fixed React Three Fiber canvas contains a horizontal comic while DOM captions and chapter titles live above it.",
      "Scroll position drives the camera through hard-authored chapter compositions.",
      "A background shader responds to scroll velocity, stretching shadow forms as movement accelerates.",
      "New chapter panels arrive separately and assemble into alignment.",
    ],
    [
      "Use a fixed spatial stage for a long-form narrative when chapter composition needs precise continuity.",
      "Scroll velocity can control atmospheric deformation while absolute scroll controls narrative position.",
      "Assemble incoming chapters from meaningful parts when the narrative metaphor is construction/arrival.",
    ],
    ["continuous-visual-anchor", "scroll-velocity-material-response", "dom-webgl-contract"],
    ["Codrops technical case study documents fixed R3F canvas, GSAP/Lenis synchronization, hard-authored frame positions and velocity-reactive GLSL."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-stefan-vitasovic-2025",
    "Stefan Vitasović Portfolio 2025",
    "https://tympanus.net/codrops/2025/03/05/case-study-stefan-vitasovic-portfolio-2025/",
    "Portfolio",
    [
      "WebGL and navigation scroll are coordinated through a custom scrolling engine.",
      "Meshes share geometry and unused project meshes are skipped to minimize overhead.",
      "Mobile preserves the interaction/motion principles while replacing the WebGL layer with HTML5 video.",
    ],
    [
      "Keep DOM and WebGL navigation on one scroll model when both respond to the same gesture.",
      "Share geometry and omit inactive meshes when the visual system is repetitive.",
      "Preserve motion grammar on mobile even if the rendering medium changes.",
    ],
    ["dom-webgl-contract", "mobile-medium-substitution", "adaptive-fidelity-not-removal"],
    ["Codrops case study documents custom scroll coordination, shared plane geometry, mesh skipping and mobile substitution with HTML5 video."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-dash-magnetic-commerce",
    "Dash Creative: Magnetic Commerce",
    "https://tympanus.net/codrops/2026/07/21/magnetic-commerce-building-the-dash-creative-website/",
    "Agency / Studio",
    [
      "The brand concept of magnetic commerce directly determines the logo's 3D cursor response.",
      "Interaction originates from a brand premise rather than being added after visual design.",
    ],
    [
      "The strongest interaction systems are consequences of the brand thesis.",
      "Before inventing a cursor behavior, ask what the brand itself should physically do.",
    ],
    ["interaction-as-thesis", "anchor-section-sets-system"],
    ["Codrops case study describes the magnetic-commerce concept as the direct origin of the rotating/pulling 3D logo interaction."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-ciel-rose",
    "Ciel Rose",
    "https://tympanus.net/codrops/2025/04/07/case-study-ciel-rose/",
    "Portfolio / Production",
    [
      "WebGL effects are applied to planes aligned with DOM media so effects feel embedded in the editorial page.",
      "Image aspect-ratio control is preserved through CMS authoring because crop is part of the art direction.",
    ],
    [
      "Use DOM-aligned WebGL planes when distortion/material effects should feel attached to editorial media.",
      "Treat aspect-ratio/crop authoring as a creative control, not only a responsive implementation detail.",
    ],
    ["dom-webgl-contract", "type-media-countermotion"],
    ["Codrops case study documents WebGL planes blended into DOM and CMS control of image formats."],
    0.97,
    "technical-reference",
  ),
  caseStudy(
    "codrops-the-spark",
    "The Spark",
    "https://tympanus.net/codrops/2026/01/09/the-spark-engineering-an-immersive-story-first-web-experience/",
    "Agency / Studio",
    [
      "The experience is conceived as a short film running in a browser rather than a marketing page with 3D decoration.",
      "Visuals, motion, pacing, sound and performance are developed as one story system.",
    ],
    [
      "Start cinematic experiences from story beats and pacing, then choose technology.",
      "Sound, motion and rendering should share the same emotional arc rather than being independently impressive.",
    ],
    ["single-signature-peak", "continuous-visual-anchor", "anchor-section-sets-system"],
    ["Codrops case study frames the project explicitly as a story-first cinematic browser experience."],
    0.96,
    "technical-reference",
  ),
  caseStudy(
    "codrops-podium",
    "Podium",
    "https://tympanus.net/codrops/2026/06/23/podium-building-a-website-where-running-becomes-storytelling/",
    "Portfolio / Film",
    [
      "The team abandoned a page-based structure in favor of one continuous sequence.",
      "Lenis is synchronized with the GSAP ticker while shared state coordinates pointer, scroll, transition phases and scene state.",
      "WebGL is reserved for specific hero/mosaic/footer systems rather than every section.",
    ],
    [
      "Choose continuous sequence architecture early when the content already has cinematic rhythm.",
      "Share one time/scroll rhythm across smooth scrolling and animation.",
      "Use WebGL selectively inside a continuous experience rather than forcing every chapter into 3D.",
    ],
    ["continuous-visual-anchor", "dom-webgl-contract", "choose-medium-by-capability"],
    ["Codrops case study documents the continuous sequence decision and shared GSAP/Lenis/Three architecture."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-arnaud-rocca",
    "Arnaud Rocca Portfolio",
    "https://tympanus.net/codrops/2026/03/31/arnaud-roccas-portfolio-from-a-gsap-powered-motion-system-to-fluid-webgl/",
    "Portfolio",
    [
      "The homepage uses one slider controlled by scroll, keyboard, bullets and drag.",
      "Project pages intentionally reduce visual complexity and use generous whitespace so work remains primary.",
      "Motion utilities and WebGL effects are designed as reusable systems rather than one-off page scripts.",
    ],
    [
      "Allow multiple input methods to drive the same state machine instead of building different experiences per input.",
      "Use restraint on detail pages even if the entry experience is highly interactive.",
      "Reusable motion primitives should preserve a coherent feel without making every page identical.",
    ],
    ["context-layer-over-world", "density-rhythm-and-silence", "anchor-section-sets-system"],
    ["Codrops case study describes multi-input slider control, restrained project layouts and reusable animation/WebGL utilities."],
    0.98,
    "technical-reference",
  ),,
  caseStudy(
    "codrops-haoqi-design",
    "HAOQI.DESIGN",
    "https://tympanus.net/codrops/2026/08/15/inside-haoqi-design-letting-dom-and-webgl-share-a-retro-futurist-stage/",
    "Portfolio",
    [
      "DOM, CSS and WebGL deliberately share one retro-futurist stage instead of being visually separated.",
      "Glass-like shader treatment and scroll synchronization reinforce a product-design-inspired identity.",
    ],
    [
      "When DOM and WebGL occupy the same visual plane, synchronize layout measurements and scroll state so they behave like one composition.",
      "Material/shader language should come from the design thesis, not from a generic glass effect preset.",
    ],
    ["dom-webgl-contract", "anchor-section-sets-system"],
    ["Codrops technical case study centers on scroll sync, glass shaders and DOM/WebGL interplay."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-cerebrium",
    "Cerebrium",
    "https://tympanus.net/codrops/2026/07/23/building-cerebrium-making-serverless-infrastructure-tangible/",
    "AI / Infrastructure",
    [
      "Abstract serverless infrastructure is explained through tangible 3D and animated path systems.",
      "Interaction behavior is designed to reflect product qualities such as speed, precision, modularity and scale.",
    ],
    [
      "Translate invisible systems into spatial metaphors only when the mapping clarifies how the product works.",
      "Let product attributes govern motion behavior so the interaction itself communicates the system.",
    ],
    ["interaction-as-thesis", "data-drives-world-state", "context-layer-over-world"],
    ["Codrops case study explicitly describes making complex AI infrastructure tangible through design, 3D and WebGL."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-trionn",
    "Trionn",
    "https://tympanus.net/codrops/2026/07/15/the-architecture-behind-trionn-coordinating-gsap-three-js-lenis-and-web-audio/",
    "Agency / Studio",
    [
      "Animation, WebGL, smooth scroll and Web Audio are coordinated as one connected framework rather than isolated section effects.",
      "Interactive hero, scroll storytelling, procedural graphics and realtime effects evolved inside a shared animation system.",
    ],
    [
      "Use one coordination layer for scroll, DOM animation, WebGL and audio state when they all participate in the same experience.",
      "A connected motion framework is more valuable than a collection of isolated effects.",
    ],
    ["dom-webgl-contract", "continuous-visual-anchor", "interaction-as-thesis"],
    ["Codrops technical case study describes GSAP, Three.js, Lenis and Web Audio as a unified responsive experience."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-the-sleepers",
    "The Sleepers",
    "https://tympanus.net/codrops/2026/07/10/the-sleepers-creating-an-atmospheric-webgl-experience-with-lightweight-techniques/",
    "Experimental / Storytelling",
    [
      "The project intentionally targets strong atmosphere through simple techniques instead of maximum technical complexity.",
      "Swirling transitions, fog, outlines and infinite-world tricks are selected for visual impact per implementation cost.",
    ],
    [
      "Prefer a small number of cheap techniques that reinforce one mood over a technically maximal stack.",
      "Judge effects by visual leverage per frame cost and production time.",
    ],
    ["choose-medium-by-capability", "atmosphere-as-layout", "effect-strength-vs-clarity"],
    ["Codrops technical case study explicitly frames the work around lightweight techniques and strongest impact with simple solutions."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-tsitsipas-digital-athlete",
    "Stefanos Tsitsipas Digital Athlete",
    "https://tympanus.net/codrops/2026/07/01/sculpting-a-digital-athlete-capturing-stefanos-tsitsipas-beyond-the-court/",
    "Sports / Portfolio",
    [
      "Photogrammetry capture produces multiple LODs but still requires web-specific texture and topology optimization.",
      "Eight body textures are consolidated into one optimized texture set.",
      "Racket strings are replaced with an alpha texture on simple geometry.",
      "Animation references real service motion frame by frame to preserve character authenticity.",
    ],
    [
      "A hero scan is only the beginning; consolidate textures, simplify geometry and preserve only the identity details the camera can reveal.",
      "Replace thin repeated geometry with alpha/textural representation when silhouette and parallax are sufficient.",
      "For recognizable people, motion authenticity can matter as much as mesh fidelity.",
    ],
    ["hero-scan-optimization", "source-structure-to-runtime-format", "authored-camera-corridor"],
    ["Codrops technical case study documents photogrammetry, LODs, UV consolidation, rigging, alpha-geometry substitution and animation matching."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-4wide",
    "4WIDE",
    "https://tympanus.net/codrops/2026/04/23/building-4wide-turning-distortion-blur-and-motion-into-a-coherent-experience/",
    "Agency / Studio",
    [
      "Distortion, blur and motion are treated as one expressive language rather than separate effects.",
      "The project explicitly balances expressiveness against message clarity and performance.",
    ],
    [
      "Choose one effect family and repeat its logic across interactions so the experience feels authored.",
      "Reduce effect strength when it starts competing with communication or frame stability.",
    ],
    ["effect-strength-vs-clarity", "anchor-section-sets-system", "density-rhythm-and-silence"],
    ["Codrops case study explicitly frames the design problem as balancing distortion/blur/motion with clarity and performance."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-false-earth",
    "False Earth",
    "https://tympanus.net/codrops/2026/04/21/false-earth-from-webgl-limits-to-a-webgpu-driven-world/",
    "Experimental / Storytelling",
    [
      "An infinite procedural landscape is built around a narrative premise rather than as a standalone technical demo.",
      "Large repeated vegetation moves to GPU/compute-style generation and indirect drawing because naive object-level rendering does not scale.",
    ],
    [
      "When the concept requires enormous repeated fields, design the data/rendering model around GPU-scale repetition instead of individual objects.",
      "Technical escalation is justified when the narrative genuinely requires scale that simpler methods cannot provide.",
    ],
    ["source-structure-to-runtime-format", "gpu-progress-transforms", "choose-medium-by-capability"],
    ["Codrops technical case study describes millions of interactive grass blades via GPU computation/indirect drawing in service of an infinite-world narrative."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-they-call-me-giulio",
    "They Call Me Giulio",
    "https://tympanus.net/codrops/2026/04/14/they-call-me-giulio-the-making-of-a-cinematic-cyberpunk-portfolio/",
    "Portfolio",
    [
      "Four cinematic scenes are developed as one coherent narrative rather than a checklist of cursor followers, oversized type and flashy effects.",
      "Animation choices are framed as story tools instead of decorative trends.",
    ],
    [
      "Reject trend checklists when they do not reinforce the experience thesis.",
      "Build scene-to-scene narrative coherence before adding signature effects.",
    ],
    ["continuous-visual-anchor", "single-signature-peak", "effect-strength-vs-clarity"],
    ["Codrops case study explicitly contrasts coherent narrative with trend-checklist creativity."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-susurrus",
    "Susurrus",
    "https://tympanus.net/codrops/2026/04/24/susurrus-crafting-a-cozy-watercolor-world-with-three-js-and-shaders/",
    "Experimental / Storytelling",
    [
      "A fully interactive 3D scene is intentionally rendered with watercolor-like non-photoreal shading.",
      "Stylization is treated as both an aesthetic choice and a performance consideration.",
      "Sound and interaction support a meditative rather than hyperactive experience.",
    ],
    [
      "Use stylized shading when it strengthens the concept and reduces the need for expensive photoreal lighting/materials.",
      "Performance strategy can be part of the art direction rather than a hidden downgrade.",
    ],
    ["stylization-as-performance", "mixed-media-world", "simulated-expensive-lighting"],
    ["Codrops case study explicitly describes NPR watercolor rendering as both aesthetic and performance consideration."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-px-push",
    "PX PUSH",
    "https://tympanus.net/codrops/2026/08/07/the-department-is-open-building-the-px-push-website/",
    "Agency / Studio",
    [
      "An old convex CRT monitor is a persistent framing device across the site, making every page feel viewed through the same 1988 machine.",
      "GSAP/ScrollTrigger effects are wired through a reusable attribute system.",
      "Lenis is manually ticked from the GSAP clock and disabled on mobile in favor of native scroll.",
      "Three separate 3D builds solve three distinct visual problems rather than one giant universal scene.",
    ],
    [
      "A persistent framing device can make unrelated content feel like one world.",
      "Centralize repeated animation behavior through declarative authoring hooks instead of one-off scripts.",
      "Use native mobile scroll when custom smooth scrolling does not improve the mobile experience.",
      "Separate 3D systems by problem when persistence would add complexity without narrative benefit.",
    ],
    ["persistent-device-metaphor", "dom-webgl-contract", "choose-medium-by-capability", "mobile-medium-substitution"],
    ["Codrops technical case study documents the persistent CRT premise, shared GSAP/Lenis clock and three separate Three.js builds."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-mersi",
    "MERSI",
    "https://tympanus.net/codrops/2026/07/27/between-print-and-digital-the-making-of-mersis-website/",
    "Architecture / Portfolio",
    [
      "The website is composed like an architectural book while interaction and motion extend the editorial logic rather than imitate print literally.",
      "Images are treated as material, typography as structure, and silence/whitespace as part of the composition.",
      "The team kept Webflow as publishing infrastructure while replacing the generic template system.",
    ],
    [
      "Borrow pacing and compositional discipline from print without forcing the browser to behave like a static page.",
      "Treat whitespace and image placement as authored material before adding motion.",
      "Keep a familiar CMS when it serves the client; replace generic design constraints rather than replacing the whole platform.",
    ],
    ["immersive-without-webgl", "density-rhythm-and-silence", "type-media-countermotion"],
    ["Codrops case study explicitly frames the site between architectural print and interactive web."],
    0.98,
    "technical-reference",
  ),
  caseStudy(
    "codrops-rk-26",
    "R—K ’26",
    "https://tympanus.net/codrops/2026/04/07/r-k-26-the-thinking-and-code-behind-a-portfolio-led-by-presence/",
    "Portfolio",
    [
      "Identity, layout, pacing, motion and brand language were repeatedly refined until they felt like one system.",
      "The final direction is defined by presence and clarity rather than by one isolated signature effect.",
    ],
    [
      "Treat identity, structure and motion as one design problem; do not lock them independently too early.",
      "A coherent presence can be the signature, even when no single WebGL spectacle dominates.",
    ],
    ["identity-rhythm-unification", "anchor-section-sets-system", "immersive-without-webgl"],
    ["Codrops case study describes year-long iteration until visual direction, motion, structure and identity converged."],
    0.96,
    "technical-reference",
  ),
  caseStudy(
    "codrops-ridgeline",
    "Ridgeline",
    "https://tympanus.net/codrops/2026/07/22/building-ridgeline-engineering-a-real-time-3d-experience-in-webflow/",
    "Travel / Portfolio",
    [
      "Real DEM elevation data is modeled in Blender, exported to glTF and rendered live in Three.js while Webflow remains the editable structure layer.",
      "A small FPS profiler records frame rate by scroll depth so optimization targets exact sections.",
      "The strongest performance wins come from stopping work that does not change pixels, including freezing static shadow maps.",
      "Known unavoidable stalls are hidden under an opaque cover rather than exposed during interaction.",
    ],
    [
      "Separate editable structure from coded behavior so creative runtime systems do not destroy content maintainability.",
      "Profile frame cost by narrative position, not only as one average FPS number.",
      "Freeze static render work and avoid recalculation before reducing visible quality.",
      "If an unavoidable initialization stall exists, schedule it behind an intentional visual cover.",
    ],
    ["freeze-static-render-work", "prewarm-signature-systems", "source-structure-to-runtime-format", "choose-medium-by-capability"],
    ["Codrops tutorial documents real terrain pipeline, scroll-depth FPS profiling, frozen shadow maps and hidden initialization stalls."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-better-off-lookback",
    "Better Off® Lookback",
    "https://tympanus.net/codrops/2026/03/03/the-lookback-a-digital-capsule-for-better-off-studios-creative-past/",
    "Archive / Studio",
    [
      "The experience is designed as a culture capsule that must work with 20 items or 200.",
      "Exploration and surprise are treated as the engagement goal rather than conversion.",
    ],
    [
      "Archive experiences need a scalable exploration model before they need signature transitions.",
      "When discovery is the objective, design for wandering and unexpected adjacency rather than funnel efficiency.",
    ],
    ["archive-as-exploration", "spatial-gallery-rhythm"],
    ["Codrops case study explicitly frames the project as a scalable culture capsule for discovery."],
    0.96,
    "technical-reference",
  ),
  caseStudy(
    "codrops-exat",
    "Exat Typeface Microsite",
    "https://tympanus.net/codrops/2026/04/10/the-exat-microsite-pushing-a-typography-showcase-to-new-creative-extremes/",
    "Typography / Culture",
    [
      "Typography itself is the primary interface; interaction reveals variable-font behavior rather than decorating it.",
      "Calm comparison sections alternate with denser expressive sections to avoid fatigue.",
      "Scroll position is treated as reversible state in pinned panels.",
      "Touch replaces ambiguous proximity interaction with a simpler fallback.",
      "Offscreen loops/interactions pause and smooth scrolling is applied selectively.",
    ],
    [
      "When the product is type, let typography become the interaction surface and the evidence.",
      "Alternate dense expressive chapters with quiet comparison chapters.",
      "Treat scroll as reversible state, not a one-way sequence of triggers.",
      "Simplify interactions on touch when the desktop gesture would lose meaning.",
      "Pause offscreen animation as part of the design system.",
    ],
    ["type-is-interface", "density-rhythm-and-silence", "mobile-medium-substitution", "freeze-static-render-work"],
    ["Codrops case study provides detailed interaction, reversible scroll, mobile fallback and performance behavior for the type specimen."],
    0.99,
    "technical-reference",
  ),
  caseStudy(
    "codrops-chems-studio",
    "Chems.Studio Archive",
    "https://tympanus.net/codrops/2026/08/08/designing-a-flexible-digital-archive-for-chems-studios-creative-practice/",
    "Portfolio / Film",
    [
      "The site is intentionally designed as an archive rather than a conventional portfolio.",
      "Projects with different contexts and rhythms are given equal importance inside one visual language.",
      "Visitors are encouraged to wander and form their own reading of the work.",
    ],
    [
      "A creative archive should preserve difference between projects while giving them one navigational grammar.",
      "Do not force every body of work into one case-study hierarchy when the desired behavior is wandering and connection-making.",
    ],
    ["archive-as-exploration", "spatial-gallery-rhythm", "density-rhythm-and-silence"],
    ["Codrops case study explicitly describes a film-led archive where visitors build their own reading across projects."],
    0.97,
    "technical-reference",
  )
];
