export type PremiumAccess = "Subscription" | "Retail" | "Trial + retail" | "Mixed";
export type PremiumSourceKind = "Library" | "Foundry";

export interface PremiumTypeSource {
  id: string;
  name: string;
  kind: PremiumSourceKind;
  access: PremiumAccess;
  url: string;
  scale: string;
  note: string;
  tags: string[];
  signatureFamilies: string[];
  verified: string;
}

export const premiumTypeSources: PremiumTypeSource[] = [
  {
    id: "fontstand",
    name: "Fontstand",
    kind: "Library",
    access: "Subscription",
    url: "https://fontstand.com/",
    scale: "70+ foundries / 23,000+ fonts",
    note: "High-end discovery and font streaming with trials, rentals and foundry subscriptions.",
    tags: ["premium", "subscription", "trials", "desktop", "web", "foundries"],
    signatureFamilies: ["Typotheque", "Commercial Type", "Process Type Foundry", "TypeTogether", "Dinamo", "OH no Type Co.", "CSTM Fonts", "Bold Monday", "DJR", "PampaType"],
    verified: "2026-09-21",
  },
  {
    id: "type-network",
    name: "Type Network",
    kind: "Library",
    access: "Retail",
    url: "https://typenetwork.com/",
    scale: "100+ represented foundries",
    note: "Enterprise-oriented premium type network with technical review, global scripts and multi-foundry licensing.",
    tags: ["premium", "enterprise", "multiscript", "variable", "retail", "foundries"],
    signatureFamilies: ["29LT", "Adobe Originals", "Bold Monday", "CSTM Fonts", "DJR", "PampaType", "Paratype", "Positype", "Contrast Foundry", "Occupant Fonts"],
    verified: "2026-09-21",
  },
  {
    id: "adobe-fonts",
    name: "Adobe Fonts",
    kind: "Library",
    access: "Subscription",
    url: "https://fonts.adobe.com/",
    scale: "5,000+ fonts",
    note: "Broad subscription library with commercial-use coverage, web projects, variable fonts and a large foundry network.",
    tags: ["premium", "subscription", "web", "variable", "foundries", "commercial-use"],
    signatureFamilies: ["Adobe Originals", "Dalton Maag", "Frere-Jones Type", "Production Type", "OH no Type Co.", "CSTM Fonts", "TypeTogether", "PampaType", "DJR", "Newlyn"],
    verified: "2026-09-21",
  },
  {
    id: "monotype-fonts",
    name: "Monotype Fonts",
    kind: "Library",
    access: "Subscription",
    url: "https://www.monotype.com/fonts",
    scale: "Enterprise font platform",
    note: "Discovery, licensing and management platform for agencies, brands and enterprise font governance.",
    tags: ["premium", "enterprise", "subscription", "governance", "licensing"],
    signatureFamilies: ["Monotype Library", "Foundry Program", "Enterprise licensing", "AI-enabled discovery"],
    verified: "2026-09-21",
  },
  {
    id: "dinamo",
    name: "Dinamo",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://abcdinamo.com/typefaces",
    scale: "45+ retail families",
    note: "Contemporary Swiss-rooted type system with strong grotesks, expressive display faces and serious global-script expansion.",
    tags: ["grotesk", "variable", "multiscript", "editorial", "fashion", "technology"],
    signatureFamilies: ["Arizona", "Asfalt", "BINGO", "Bubblegum", "Camera", "Camera Rounded", "Connect", "Cowboy", "Daily", "Diatype", "Diatype Extra", "Diatype Rounded", "Estragon", "Favorit", "Gaisyr", "Galapagos", "Ginto", "Ginto Rounded", "Gramercy", "Gravity", "Grow", "Helveesti", "Honeymoon", "Ikarus", "Laica", "Marfa", "Marist", "Maxi", "Monument Grotesk", "Oracle", "Oracle Rounded", "Otto", "Paloma", "Pareto", "Pelikan", "Prophet", "Publisher", "ROM", "Repro", "Schengen", "Social", "Solar", "Stefan", "Synt", "Walter", "Whyte"],
    verified: "2026-09-21",
  },
  {
    id: "grilli-type",
    name: "Grilli Type",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://www.grillitype.com/typefaces",
    scale: "21 core families",
    note: "Contemporary Swiss-tradition foundry with strong brand, editorial and high-performance grotesk systems.",
    tags: ["swiss", "grotesk", "editorial", "brand", "variable", "multiscript"],
    signatureFamilies: ["GT Alpina", "GT America", "GT America Intl", "GT Canon", "GT Cinetype", "GT Eesti", "GT Era", "GT Flaire", "GT Flexa", "GT Haptik", "GT Maru", "GT Mechanik", "GT Pantheon", "GT Planar", "GT Pressura", "GT Sectra", "GT Standard", "GT Super", "GT Ultra", "GT Walsheim", "GT Zirkon"],
    verified: "2026-09-21",
  },
  {
    id: "commercial-type",
    name: "Commercial Type",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://commercialtype.com/catalog",
    scale: "Deep editorial + brand catalog",
    note: "High-end type for editorial, fashion, culture and identity with extensive families and mature language support.",
    tags: ["editorial", "luxury", "fashion", "brand", "serif", "grotesk"],
    signatureFamilies: ["Graphik", "Graphik Wide", "Canela", "Canela Text", "Feature", "Lyon", "Caponi", "Darby Serif", "Orleans", "Orlando", "Druk", "Sanomat", "Guardian Sans"],
    verified: "2026-09-21",
  },
  {
    id: "klim",
    name: "Klim Type Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://klim.co.nz/",
    scale: "Focused premium catalog",
    note: "Highly influential contemporary type library spanning refined grotesks, editorial serif systems and corporate families.",
    tags: ["grotesk", "editorial", "corporate", "luxury", "serif", "sans"],
    signatureFamilies: ["Die Grotesk", "American Grotesk", "Martina Plantijn", "The Future", "The Future Mono", "Founders Grotesk", "Founders Grotesk Condensed", "Founders Grotesk X-Condensed", "Founders Grotesk Text", "Founders Grotesk Mono", "National 2", "Söhne", "Söhne Mono", "Söhne Schmal", "Söhne Breit", "Tiempos Fine", "Tiempos Headline", "Tiempos Text", "Untitled Sans", "Untitled Serif"],
    verified: "2026-09-21",
  },
  {
    id: "pangram-pangram",
    name: "Pangram Pangram",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://pangrampangram.com/collections/fonts",
    scale: "62 fonts",
    note: "Modern display and workhorse families with extensive variable cuts and free-to-try licensing.",
    tags: ["variable", "fashion", "editorial", "display", "grotesk", "brutalist"],
    signatureFamilies: ["Neue Gstaad", "Palma", "Neue Montreal", "Neue York"],
    verified: "2026-09-21",
  },
  {
    id: "displaay",
    name: "Displaay",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://displaay.net/typefaces",
    scale: "33 families",
    note: "Distinctive independent retail library with full trials and strong contemporary brand typography.",
    tags: ["brand", "grotesk", "display", "serif", "variable", "editorial"],
    signatureFamilies: ["Aguzzo", "Avantt", "Azeret", "Bagoss", "Booton", "Concrette", "Coolkit", "Coxx", "Dazzed", "Denim", "Documan", "Fellix", "Fenul", "Gellix", "Greed", "Haffer", "Hellix", "Jokker", "Lazzer", "Matter", "Ofform", "Panell", "Perfektta", "Post", "Reckless", "Roobert", "Saans", "Season", "Serrif", "Teodor", "Tobias", "Wallop", "Yellix"],
    verified: "2026-09-21",
  },
  {
    id: "swiss-typefaces",
    name: "Swiss Typefaces",
    kind: "Foundry",
    access: "Retail",
    url: "https://www.swisstypefaces.com/",
    scale: "20+ published systems",
    note: "Premium Swiss systems ranging from utilitarian international grotesks to editorial serif and experimental display families.",
    tags: ["swiss", "grotesk", "luxury", "editorial", "mono", "brand"],
    signatureFamilies: ["Black Mamba", "BRRR", "Euclid", "Euclid Mono", "Euclid Stencil", "IKANSEEYOUALL", "KOPYME", "KRSNA", "Only", "NewPanam", "NewParis", "Raskal Oner", "Riviera", "SangBleu", "SangBleu OG", "Simplon", "Suisse", "TheW", "Vogy Smog", "Write"],
    verified: "2026-09-21",
  },
  {
    id: "production-type",
    name: "Production Type",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://productiontype.com/fonts",
    scale: "80+ typefaces / 800+ styles",
    note: "Paris and Shanghai type design agency with retail, luxury, industrial and media expertise.",
    tags: ["editorial", "luxury", "industrial", "media", "multiscript", "brand"],
    signatureFamilies: ["Cardinal", "PVC", "Wigrum", "Kessler", "NSType", "Peignot", "Peignot Jumbo", "Terrane Sans", "Terrane Serif", "Graphika81", "Enduro", "Media Sans", "Signal Compressed"],
    verified: "2026-09-21",
  },
  {
    id: "typotheque",
    name: "Typotheque",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://www.typotheque.com/fonts",
    scale: "Large multiscript library",
    note: "Premium global type systems with deep script coverage and serious digital typography engineering.",
    tags: ["multiscript", "global", "editorial", "ui", "display", "mono"],
    signatureFamilies: ["Chairman", "Chairman Semi-Mono", "Chairman Text", "Chairman Mono", "Chairman Display", "Terrassa", "Terrassa Gradient", "Terrassa Display", "Pristine", "Zed", "Zed Text", "Zed Round", "Zed Display", "Vita"],
    verified: "2026-09-21",
  },
  {
    id: "ohno",
    name: "OH no Type Co.",
    kind: "Foundry",
    access: "Retail",
    url: "https://ohnotype.co/fonts",
    scale: "26 families",
    note: "Expressive, high-character contemporary type with strong optical-size thinking and unconventional display systems.",
    tags: ["expressive", "display", "editorial", "variable", "serif", "sans"],
    signatureFamilies: ["Beastly", "Camelion", "Casserole", "Cheee", "Compadre", "Coniferous", "Covik", "Degular", "Eckmannpsych", "Forevs", "Hobeaux", "Hobeaux Rococeaux", "Irregardless", "Montreuil", "Obviously", "Ohno Blazeface", "Ohno Casual", "Ohno Fatface", "Ohno Softie", "Polymath", "Regrets", "Retail", "Swear", "Viktor Script", "Vulf", "Yumex"],
    verified: "2026-09-21",
  },
  {
    id: "black-foundry",
    name: "Black[Foundry]",
    kind: "Foundry",
    access: "Retail",
    url: "https://black-foundry.com/fonts/",
    scale: "40+ families",
    note: "Large contemporary retail catalog with extensive variable systems and brand-ready text/display families.",
    tags: ["variable", "brand", "display", "serif", "sans", "mono"],
    signatureFamilies: ["Algo", "Ampere", "Angus", "Aubusson", "Beaurencourt", "Blaacck", "Bluu Suuperstar", "Booster Next", "Brillante", "Caesura", "Canberra", "Clother", "Coco", "Drive", "Drive Mono", "Drive Prop", "Egitto", "Exquise", "Fat", "Finder", "Galien", "Gauthier", "Grtsk", "Ilya", "Jack", "Kefa III", "Marianina", "Minorca", "Numero 02", "Raconteurs", "Respublika", "Rowton", "Rowton Stencil", "Squil", "Tonos", "Tonos Mono", "Tosh", "Vanille", "Vesterbro", "Vesterbro Sans", "Vicomte", "Yocco"],
    verified: "2026-09-21",
  },
  {
    id: "process-type",
    name: "Process Type Foundry",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://processtypefoundry.com/",
    scale: "34 families",
    note: "Long-running independent foundry known for practical, distinctive systems used across identity, UI and editorial design.",
    tags: ["ui", "brand", "editorial", "sans", "serif", "display"],
    signatureFamilies: ["Adjunct", "Anchor", "Bryant 2", "Bryant Pro", "Bryant Compressed", "Bryant Condensed", "Capucine", "Colfax", "Coordinates", "Elena", "FIG", "FindReplace", "Indivisible", "Kettler", "Klavika", "Klavika Condensed", "Klavika Display", "Landform", "Lingua", "Locator", "Locator Display", "Maple", "Moniker", "Pique", "Recent Grotesk", "Recipient", "Scandia", "Scandia Line", "Sculpin", "Seravek", "Stratum 1", "Stratum 2", "Stratum Condensed"],
    verified: "2026-09-21",
  },
  {
    id: "newlyn",
    name: "Newlyn",
    kind: "Foundry",
    access: "Retail",
    url: "https://newlyn.com/fonts",
    scale: "15+ commercial collections",
    note: "Commercial brand typography spanning serif, sans, display, mono, condensed and extended families.",
    tags: ["brand", "identity", "editorial", "web", "corporate", "display"],
    signatureFamilies: ["New Atlas", "New Vision", "New Science", "New Spirit", "New Kansas", "New Astro", "New Order", "New Hero", "New Atten", "New Frank", "New Herman", "New Reason", "New Rubrik", "New Zen", "New Farm"],
    verified: "2026-09-21",
  },
  {
    id: "sharp-type",
    name: "Sharp Type",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://www.sharptype.co/typefaces",
    scale: "Global-script contemporary catalog",
    note: "High-end display, text and grotesk systems with expanding Hangul, Thai, Arabic, Devanagari and Pan-European coverage.",
    tags: ["multiscript", "display", "grotesk", "editorial", "variable", "brand"],
    signatureFamilies: ["Sharp Grotesk", "Post Grotesk", "Alpes", "Alpes Mono", "Carta Nueva", "Ceraph", "Cordier Script", "DOSS", "Eterne Display", "Eterne Text", "Ghost Display", "Ghost Display SemiMono", "Ghost Display Mono"],
    verified: "2026-09-21",
  },
  {
    id: "fort-foundry",
    name: "Fort Foundry",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://fortfoundry.com/fonts",
    scale: "Broad retail library",
    note: "Highly usable commercial families ranging from geometric workhorses to expressive scripts and retro display systems.",
    tags: ["brand", "display", "sans", "script", "industrial", "retro"],
    signatureFamilies: ["Kodachrome", "East Bay", "Silverberg", "Molfetta", "Abolition", "Alkaline", "Beale", "Bearklaw", "Beverly Drive", "Beverly Drive Right", "Termina", "Industry"],
    verified: "2026-09-21",
  },
  {
    id: "fontfabric",
    name: "Fontfabric",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://www.fontfabric.com/",
    scale: "Large commercial catalog",
    note: "Commercial family library with strong geometric, product, app and brand-oriented typography.",
    tags: ["brand", "ui", "app", "geometric", "sans", "slab"],
    signatureFamilies: ["Nexa", "Intro", "Mont", "Panton", "Nexa Slab", "Rizo"],
    verified: "2026-09-21",
  },
  {
    id: "type-together",
    name: "TypeTogether",
    kind: "Foundry",
    access: "Retail",
    url: "https://www.type-together.com/",
    scale: "80 families via Fontstand",
    note: "Award-winning text and interface type with broad language support and strong screen typography expertise.",
    tags: ["ui", "editorial", "multiscript", "text", "screen", "global"],
    signatureFamilies: ["Abril", "Literata"],
    verified: "2026-09-21",
  },
  {
    id: "positype",
    name: "Positype",
    kind: "Foundry",
    access: "Retail",
    url: "https://typenetwork.com/type-foundries",
    scale: "210+ families",
    note: "Large independent library spanning Latin, Arabic, Khmer, Thai, Cyrillic, Greek and more.",
    tags: ["multiscript", "global", "brand", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "29lt",
    name: "29LT",
    kind: "Foundry",
    access: "Retail",
    url: "https://typenetwork.com/type-foundries",
    scale: "36 families via Fontstand",
    note: "Premium multi-script specialist known for integrated Arabic and Latin typography.",
    tags: ["arabic", "latin", "multiscript", "global", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "cstm-fonts",
    name: "CSTM Fonts",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "61 families / 596 fonts via Fontstand",
    note: "Award-winning contemporary type foundry with deep Latin and Cyrillic expertise.",
    tags: ["cyrillic", "latin", "editorial", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "bold-monday",
    name: "Bold Monday",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "39 families / 487 fonts via Fontstand",
    note: "Carefully engineered contemporary retail and custom typography for editorial and identity systems.",
    tags: ["editorial", "brand", "ui", "text"],
    signatureFamilies: ["Dico Sans"],
    verified: "2026-09-21",
  },
  {
    id: "dj-r",
    name: "DJR",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "61 families / 631 fonts via Fontstand",
    note: "David Jonathan Ross library spanning expressive display faces and highly practical text systems.",
    tags: ["display", "text", "variable", "experimental"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "typofonderie",
    name: "Typofonderie",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "86 families / 488 fonts via Fontstand",
    note: "Large premium European catalog covering text, editorial, signage and corporate typography.",
    tags: ["editorial", "corporate", "text", "signage"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "indian-type-foundry",
    name: "Indian Type Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "105 families / 767 fonts via Fontstand",
    note: "Large multi-script foundry with strong South Asian and global type coverage.",
    tags: ["multiscript", "indic", "global", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "playtype",
    name: "Playtype",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "111 families / 1,314 fonts via Fontstand",
    note: "Large Copenhagen-rooted premium library spanning functional and expressive contemporary typography.",
    tags: ["brand", "display", "sans", "serif"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "cast",
    name: "CAST",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "112 families / 990 fonts via Fontstand",
    note: "Broad premium type library with serious editorial and display coverage.",
    tags: ["editorial", "display", "text", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "type-mates",
    name: "TypeMates",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "77 families / 1,016 fonts via Fontstand",
    note: "Contemporary type foundry with extensive family systems and strong brand-use coverage.",
    tags: ["brand", "corporate", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "zetafonts",
    name: "Zetafonts",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "79 families / 1,199 fonts via Fontstand",
    note: "Large contemporary retail library with broad display and brand typography coverage.",
    tags: ["display", "brand", "editorial", "sans", "serif"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "storm-type",
    name: "Storm Type Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "115 families / 1,630 fonts via Fontstand",
    note: "Deep Central European type library with extensive editorial and historical range.",
    tags: ["editorial", "historic", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "suitcase",
    name: "Suitcase Type Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "38 families / 544 fonts via Fontstand",
    note: "Award-winning premium foundry with broad editorial, brand and multi-style systems.",
    tags: ["editorial", "brand", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "pampatype",
    name: "PampaType",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "28 families / 176 fonts via Fontstand",
    note: "Argentinian studio developing high-quality retail and bespoke type systems.",
    tags: ["editorial", "brand", "latin", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "signal",
    name: "Signal Type Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "20 families / 363 fonts via Fontstand",
    note: "Contemporary identity-focused foundry with distinctive editorial and display families.",
    tags: ["brand", "display", "editorial"],
    signatureFamilies: ["Ballinger Condensed"],
    verified: "2026-09-21",
  },
  {
    id: "contrast-foundry",
    name: "Contrast Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://typenetwork.com/type-foundries",
    scale: "14 families / 213 fonts via Fontstand",
    note: "Global studio focused on crisp contemporary letterforms and high-performance interface typography.",
    tags: ["ui", "brand", "grotesk", "global"],
    signatureFamilies: ["CoFo Gothic"],
    verified: "2026-09-21",
  },
  {
    id: "alias",
    name: "Alias",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "32 families / 167 fonts via Fontstand",
    note: "Independent foundry known for fashion, editorial and highly recognizable identity typography.",
    tags: ["fashion", "editorial", "display", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "ek-type",
    name: "Ek Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "57 families / 669 fonts via Fontstand",
    note: "Indian collective focused on multilingual type families for diverse scripts and contexts.",
    tags: ["multiscript", "indic", "global", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "nova",
    name: "Nova Type Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "11 families / 126 fonts via Fontstand",
    note: "Independent contemporary foundry focused on carefully built family systems.",
    tags: ["brand", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "type-republic",
    name: "TypeRepublic",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "10 families / 45 fonts via Fontstand",
    note: "Barcelona-based premium type design with distinctive editorial character.",
    tags: ["editorial", "display", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "setup-type",
    name: "Setup Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "12 families / 94 fonts via Fontstand",
    note: "Independent foundry with compact, high-craft contemporary type systems.",
    tags: ["brand", "editorial", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "darden",
    name: "Darden Studio",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "15 families / 233 fonts via Fontstand",
    note: "Premium editorial and identity type studio with substantial family systems.",
    tags: ["editorial", "brand", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "xyz",
    name: "XYZ Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "6 families / 57 fonts via Fontstand",
    note: "Small premium foundry focused on highly resolved contemporary families.",
    tags: ["brand", "editorial", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "coppers-brasses",
    name: "Coppers and Brasses",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "9 families / 66 fonts via Fontstand",
    note: "Montreal type foundry with distinctive contemporary text and display families.",
    tags: ["brand", "mono", "display", "text"],
    signatureFamilies: ["Martha"],
    verified: "2026-09-21",
  },
  {
    id: "letterror",
    name: "LettError Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "11 families / 44 fonts via Fontstand",
    note: "Experimental and technically sophisticated Dutch type design with a strong digital lineage.",
    tags: ["experimental", "digital", "editorial", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "ludwigtype",
    name: "LudwigType",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "17 families / 239 fonts via Fontstand",
    note: "Independent premium foundry focused on high-quality retail, custom lettering and brand typography.",
    tags: ["brand", "editorial", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "retype",
    name: "Retype",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "9 families / 93 fonts via Fontstand",
    note: "Amsterdam-rooted type studio known for polished editorial and identity families.",
    tags: ["editorial", "brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "type-supply",
    name: "Type Supply",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "8 families / 93 fonts via Fontstand",
    note: "Tal Leming's tightly engineered retail families for editorial, interface and identity work.",
    tags: ["ui", "brand", "text", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "feliciano-type",
    name: "Feliciano Type",
    kind: "Foundry",
    access: "Trial + retail",
    url: "https://fontstand.com/",
    scale: "15 families / 150 fonts via Fontstand",
    note: "Mário Feliciano's premium library spanning geometric sans, editorial families and serious publication typography.",
    tags: ["editorial", "geometric", "sans", "publication"],
    signatureFamilies: ["Flama"],
    verified: "2026-09-21",
  },
  {
    id: "house-industries",
    name: "House Industries",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "24 families via Fontstand",
    note: "Highly recognizable display and identity typography with a deep American lettering sensibility.",
    tags: ["display", "identity", "retro", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "typejockeys",
    name: "Typejockeys",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "14 families / 120 fonts via Fontstand",
    note: "Vienna-based foundry producing refined retail and custom families for editorial and brand work.",
    tags: ["editorial", "brand", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "okay-type",
    name: "Okay Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "9 families / 120 fonts via Fontstand",
    note: "Independent contemporary type studio with carefully engineered family systems.",
    tags: ["brand", "text", "sans", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "just-another-foundry",
    name: "Just Another Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "22 families / 261 fonts via Fontstand",
    note: "Independent premium foundry with a broad catalog of highly usable text and display families.",
    tags: ["text", "display", "brand", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "tptq-arabic",
    name: "TPTQ Arabic",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "23 families / 151 fonts via Fontstand",
    note: "Premium Arabic-script type library extending Typotheque's global typography expertise.",
    tags: ["arabic", "multiscript", "global", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "mckl",
    name: "MCKL",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "10 families / 221 fonts via Fontstand",
    note: "Jeremy Mickel's premium type studio spanning editorial, identity and practical contemporary systems.",
    tags: ["editorial", "brand", "text", "sans"],
    signatureFamilies: ["Owners"],
    verified: "2026-09-21",
  },
  {
    id: "blackletra",
    name: "Blackletra",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "20 families / 185 fonts via Fontstand",
    note: "Latin American premium type library with strong editorial and expressive display character.",
    tags: ["editorial", "display", "latin", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "sandoll",
    name: "Sandoll",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "4 families / 30 fonts via Fontstand",
    note: "Major Korean type company represented in Fontstand's premium foundry network.",
    tags: ["korean", "multiscript", "global", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "r-typography",
    name: "R-Typography",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "51 families / 497 fonts via Fontstand",
    note: "Large independent premium library spanning contemporary text and display typography.",
    tags: ["text", "display", "brand", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "fontef",
    name: "Fontef",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "10 families / 46 fonts via Fontstand",
    note: "Independent premium type foundry represented in Fontstand's curated network.",
    tags: ["brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "emtype",
    name: "Emtype Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "33 families / 630 fonts via Fontstand",
    note: "Barcelona-based premium catalog with substantial editorial, display and identity families.",
    tags: ["editorial", "display", "brand", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "type-o-tones",
    name: "Type-Ø-Tones",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "8 families / 73 fonts via Fontstand",
    note: "Experimental Barcelona type collective with distinctive cultural and display-focused families.",
    tags: ["experimental", "culture", "display", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "muccatypo",
    name: "muccaTypo",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "7 families / 57 fonts via Fontstand",
    note: "Boutique premium type library rooted in high-end branding and identity design.",
    tags: ["luxury", "brand", "identity", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "tlab-font",
    name: "Tlab font",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "57 families / 106 fonts via Fontstand",
    note: "Large independent retail catalog represented through Fontstand's curated network.",
    tags: ["display", "brand", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "questa-project",
    name: "The Questa Project",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "5 families / 80 fonts via Fontstand",
    note: "Focused premium family system built for editorial, display and book typography.",
    tags: ["editorial", "book", "serif", "sans"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "barnbrook",
    name: "Barnbrook Fonts",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "34 families / 160 fonts via Fontstand",
    note: "Expressive premium display typography with a strong cultural and graphic-design pedigree.",
    tags: ["culture", "display", "experimental", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "kontour",
    name: "Kontour",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "12 families / 141 fonts via Fontstand",
    note: "Sibylle Hagmann's premium type studio balancing expressive voice and text usability.",
    tags: ["editorial", "text", "brand", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "arphic-types",
    name: "Arphic Types",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "103 families / 165 fonts via Fontstand",
    note: "Large Asian type provider represented in Fontstand's premium ecosystem.",
    tags: ["cjk", "multiscript", "global", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "original-type",
    name: "Original Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "7 families / 118 fonts via Fontstand",
    note: "Independent premium foundry centered on authentic, high-quality contemporary families.",
    tags: ["brand", "text", "display", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "pyte-foundry",
    name: "The Pyte Foundry",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "12 families / 40 fonts via Fontstand",
    note: "Independent foundry in Fontstand's premium network with compact contemporary family systems.",
    tags: ["brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "nouvelle-noire",
    name: "Nouvelle Noire",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "35 families / 320 fonts via Fontstand",
    note: "Swiss independent foundry with distinctive contemporary retail and custom typography.",
    tags: ["swiss", "brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "superior-type",
    name: "Superior Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "44 families / 509 fonts via Fontstand",
    note: "Large premium retail catalog spanning practical brand, editorial and display systems.",
    tags: ["brand", "editorial", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "cadson-demak",
    name: "Cadson Demak",
    kind: "Foundry",
    access: "Retail",
    url: "https://typenetwork.com/type-foundries",
    scale: "9 families / 39 fonts via Fontstand",
    note: "High-profile Thai foundry and consultancy specializing in Thai and Latin type systems.",
    tags: ["thai", "latin", "multiscript", "global"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "tiny-type",
    name: "Tiny Type Co.",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "7 families / 43 fonts via Fontstand",
    note: "Small premium independent studio represented in Fontstand's curated library.",
    tags: ["brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "dizajndesign",
    name: "DizajnDesign",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "24 families / 195 fonts via Fontstand",
    note: "Central European premium foundry with expressive editorial and identity families.",
    tags: ["editorial", "brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "liebefonts",
    name: "LiebeFonts",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "7 families / 35 fonts via Fontstand",
    note: "Boutique premium family collection with a strong hand-made and expressive voice.",
    tags: ["display", "script", "expressive", "brand"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "supertype",
    name: "supertype®",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "24 families / 281 fonts via Fontstand",
    note: "Premium independent library covering brand, editorial and contemporary display typography.",
    tags: ["brand", "editorial", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "hot-type",
    name: "Hot Type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "12 families / 104 fonts via Fontstand",
    note: "Independent premium type foundry with contemporary display and identity-focused work.",
    tags: ["display", "brand", "editorial"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "mass-driver",
    name: "Mass-Driver",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "12 families / 146 fonts via Fontstand",
    note: "Premium independent foundry represented in Fontstand's design-led ecosystem.",
    tags: ["brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "bvh-type",
    name: "bvh type",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "16 families / 122 fonts via Fontstand",
    note: "Independent European foundry producing carefully crafted contemporary families.",
    tags: ["brand", "editorial", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "halbfett",
    name: "Halbfett",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "12 families / 129 fonts via Fontstand",
    note: "Premium independent family collection represented through Fontstand.",
    tags: ["brand", "display", "text"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "brink",
    name: "Brink",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "13 families / 204 fonts via Fontstand",
    note: "Contemporary premium foundry with a compact but substantial family catalog.",
    tags: ["brand", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
  {
    id: "teeline",
    name: "Teeline Fonts",
    kind: "Foundry",
    access: "Retail",
    url: "https://fontstand.com/",
    scale: "14 families / 76 fonts via Fontstand",
    note: "Independent premium font library represented through Fontstand's curated platform.",
    tags: ["brand", "text", "display"],
    signatureFamilies: [],
    verified: "2026-09-21",
  },
];

export const premiumLibraries = premiumTypeSources.filter((source) => source.kind === "Library");
export const premiumFoundries = premiumTypeSources.filter((source) => source.kind === "Foundry");

export const premiumSignatureFamilyCount = premiumTypeSources.reduce(
  (total, source) => total + source.signatureFamilies.length,
  0,
);
