import { Buffer } from "node:buffer";
import { parseExperience } from "@/src/lib/configSchema";
import { parseAssetManifest } from "@/src/platform/assetManifestSchema";
import { parseStudioProject } from "@/src/platform/studioSchema";

export interface StudioPublishInput {
  experience: unknown;
  project: unknown;
  assetManifest: unknown;
  title?: string;
  summary?: string;
}

export interface StudioPublishEnvironment {
  repository: string;
  token: string;
}

export async function publishStudioDraft(input: StudioPublishInput, environment: StudioPublishEnvironment, fetcher: typeof fetch = fetch) {
  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(environment.repository)) throw new Error("FORGE_GITHUB_REPOSITORY must use owner/name");
  if (!environment.token) throw new Error("FORGE_GITHUB_TOKEN is missing");
  const experience = parseExperience(input.experience);
  const project = parseStudioProject(input.project);
  const assetManifest = parseAssetManifest(input.assetManifest);
  const base = project.deployment.productionBranch;
  if (!/^[A-Za-z0-9._/-]+$/.test(base) || base.includes("..")) throw new Error("Invalid production branch");
  const stamp = new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0, 14);
  const branch = `forge/studio-${project.id}-${stamp}`;
  const api = `https://api.github.com/repos/${environment.repository}`;
  const headers = { accept: "application/vnd.github+json", authorization: `Bearer ${environment.token}`, "content-type": "application/json", "x-github-api-version": "2022-11-28" };
  const request = async <T>(url: string, init?: RequestInit): Promise<T> => {
    const response = await fetcher(url, { ...init, headers: { ...headers, ...init?.headers }, cache: "no-store" });
    if (!response.ok) {
      const body = await response.text();
      throw new Error(`GitHub request failed (${response.status}): ${body.slice(0, 180)}`);
    }
    return response.json() as Promise<T>;
  };
  const ref = await request<{ object: { sha: string } }>(`${api}/git/ref/heads/${encodeURIComponent(base)}`);
  await request(`${api}/git/refs`, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: ref.object.sha }) });
  const projectPath = project.experiencePath.includes("/") ? project.experiencePath.replace(/[^/]+$/, "studio-project.json") : "studio-project.json";
  const files = [
    { path: project.experiencePath, value: experience },
    { path: projectPath, value: project },
    { path: "config/asset-manifest.json", value: assetManifest },
  ];
  for (const file of files) {
    const current = await request<{ sha: string }>(`${api}/contents/${file.path}?ref=${encodeURIComponent(branch)}`);
    await request(`${api}/contents/${file.path}`, { method: "PUT", body: JSON.stringify({ message: `Update ${file.path} from Forge Studio`, content: Buffer.from(JSON.stringify(file.value, null, 2) + "\n").toString("base64"), branch, sha: current.sha }) });
  }
  const title = cleanText(input.title, 100) || `Update ${project.name} from Forge Studio`;
  const summary = cleanText(input.summary, 600) || "Validated visual-authoring update from Forge Studio.";
  const pull = await request<{ number: number; html_url: string }>(`${api}/pulls`, { method: "POST", body: JSON.stringify({ title, head: branch, base, body: `${summary}\n\nGenerated by Forge Studio after local schema validation. Binary assets must already exist at their registered public paths.` }) });
  return { branch, number: pull.number, url: pull.html_url };
}

function cleanText(value: string | undefined, max: number) {
  return (value ?? "").replace(/[<>\u0000-\u001f]/g, " ").trim().slice(0, max);
}
