import { Buffer } from "node:buffer";
import { parseExperience } from "@/src/lib/configSchema";
import { parseAssetManifest } from "@/src/platform/assetManifestSchema";
import { parseStudioProject } from "@/src/platform/studioSchema";
import { parseCinematicSystems } from "@/src/lib/cinematic/schema";
import { parseInteractionGraph } from "@/src/lib/interactionGraph";

export interface StudioPublishInput {
  experience: unknown;
  project: unknown;
  assetManifest: unknown;
  interactionGraph: unknown;
  cinematicSystems?: unknown;
  title?: string;
  summary?: string;
}

export interface StudioPublishEnvironment {
  repository: string;
  token: string;
}

export async function publishStudioDraft(input: StudioPublishInput, environment: StudioPublishEnvironment, fetcher: typeof fetch = fetch) {
  if (!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(environment.repository)) throw new Error("FORGE_GITHUB_REPOSITORY must use owner/name");
  if (!environment.token) throw new Error("FORGE_GITHUB_TOKEN is missing");
  const experience = parseExperience(input.experience);
  const project = parseStudioProject(input.project);
  const assetManifest = parseAssetManifest(input.assetManifest);
  const interactionGraph = parseInteractionGraph(input.interactionGraph);
  const cinematicSystems = input.cinematicSystems ? parseCinematicSystems(input.cinematicSystems) : null;
  const base = project.deployment.productionBranch;
  if (!/^[A-Za-z0-9._/-]+$/.test(base) || base.includes("..")) throw new Error("Invalid production branch");
  const stamp = new Date().toISOString().replace(/[-:TZ.]/g, "").slice(0, 14);
  const branch = `forge/studio-${project.id}-${stamp}`;
  const api = `https://api.github.com/repos/${environment.repository}`;
  const headers = { accept: "application/vnd.github+json", authorization: `Bearer ${environment.token}`, "content-type": "application/json", "x-github-api-version": "2022-11-28" };
  const request = async <T>(url: string, init?: RequestInit): Promise<T> => {
    const response = await fetcher(url, { ...init, headers: { ...headers, ...init?.headers }, cache: "no-store" });
    if (!response.ok) {
      const body = await response.text();
      throw new Error(`GitHub request failed (${response.status}): ${body.slice(0, 180)}`);
    }
    return response.json() as Promise<T>;
  };
  const ref = await request<{ object: { sha: string } }>(`${api}/git/ref/heads/${encodeURIComponent(base)}`);
  await request(`${api}/git/refs`, { method: "POST", body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: ref.object.sha }) });
  const paths=studioPublishPaths(project);
  const files = [
    { path: project.experiencePath, value: experience },
    { path: paths.project, value: project },
    { path: paths.assetManifest, value: assetManifest },
    { path: paths.interactionGraph, value: interactionGraph },
    ...(cinematicSystems ? [{ path: paths.cinematicSystems, value: cinematicSystems }] : []),
  ];
  for (const file of files) {
    const current = await readExistingFileSha(`${api}/contents/${file.path}?ref=${encodeURIComponent(branch)}`, headers, fetcher);
    const body:{message:string;content:string;branch:string;sha?:string}={
      message:`Update ${file.path} from Forge Studio`,
      content:Buffer.from(JSON.stringify(file.value, null, 2) + "\n").toString("base64"),
      branch,
    };
    if(current) body.sha=current;
    await request(`${api}/contents/${file.path}`, { method: "PUT", body: JSON.stringify(body) });
  }
  const title = cleanText(input.title, 100) || `Update ${project.name} from Forge Studio`;
  const summary = cleanText(input.summary, 600) || "Validated visual-authoring update from Forge Studio.";
  const pull = await request<{ number: number; html_url: string }>(`${api}/pulls`, { method: "POST", body: JSON.stringify({ title, head: branch, base, body: `${summary}\n\nGenerated by Forge Studio after local schema validation. Binary assets must already exist at their registered public paths.` }) });
  return { branch, number: pull.number, url: pull.html_url };
}

function cleanText(value: string | undefined, max: number) {
  return (value ?? "").replace(/[<>\u0000-\u001f]/g, " ").trim().slice(0, max);
}


export function studioPublishPaths(project:StudioPublishProject) {
  const experienceRoot=parentDirectory(project.experiencePath);
  const projectRoot=projectConfigRoot(project);
  return {
    project:joinJsonPath(projectRoot,"studio-project.json"),
    assetManifest:joinJsonPath(experienceRoot,"asset-manifest.json"),
    interactionGraph:joinJsonPath(projectRoot,"interaction-graph.json"),
    cinematicSystems:joinJsonPath(projectRoot,"cinematic-systems.json"),
  };
}

type StudioPublishProject=ReturnType<typeof parseStudioProject>;

function projectConfigRoot(project:StudioPublishProject) {
  const candidates=[project.visualSystemsPath,project.creativeDirectionPath,project.experienceModesPath];
  const client=candidates.find((value)=>value.startsWith("clients/"));
  return parentDirectory(client ?? project.experiencePath);
}

function parentDirectory(value:string) {
  const index=value.lastIndexOf("/");
  return index>=0 ? value.slice(0,index) : "";
}

function joinJsonPath(root:string,name:string) {
  return root ? `${root}/${name}` : name;
}

async function readExistingFileSha(
  url:string,
  headers:Record<string,string>,
  fetcher:typeof fetch,
) {
  const response=await fetcher(url,{headers,cache:"no-store"});
  if(response.status===404) return undefined;
  if(!response.ok) throw new Error(`GitHub request failed (${response.status}): ${(await response.text()).slice(0,180)}`);
  const body=await response.json() as {sha?:unknown};
  return typeof body.sha==="string" ? body.sha : undefined;
}
